/**
 *  @file   KeyMap.cpp
 *	
 *  @date   Apr 20, 2019
 *  @author Michael DesRoches, Alexander Pasinski, and Gianni Pinneri
 *
 *  @brief  
 */

#include <Utilities/KeyMap.h>

std::map<std::string, OIS::KeyCode> KeyMap = 
{
        {"UNASSIGNED", OIS::KC_UNASSIGNED}   ,
        {"ESCAPE", OIS::KC_ESCAPE}       ,
        {"1", OIS::KC_1}            ,
        {"2", OIS::KC_2}            ,
        {"3", OIS::KC_3}           ,
        {"4", OIS::KC_4}            ,
        {"5", OIS::KC_5}           ,
        {"6", OIS::KC_6}           ,
        {"7", OIS::KC_7}           ,
        {"8", OIS::KC_8}           ,
        {"9", OIS::KC_9}           ,
        {"0", OIS::KC_0}           ,
        {"-", OIS::KC_MINUS}        ,
        {"=", OIS::KC_EQUALS}       ,
        {"BACK", OIS::KC_BACK}         ,
        {"TAB", OIS::KC_TAB}          ,
        {"Q", OIS::KC_Q}            ,
        {"W", OIS::KC_W}            ,
        {"E", OIS::KC_E}            ,
        {"R", OIS::KC_R}            ,
        {"T", OIS::KC_T}            ,
        {"Y", OIS::KC_Y}            ,
        {"U", OIS::KC_U}            ,
        {"I", OIS::KC_I}            ,
        {"O", OIS::KC_O}            ,
        {"P", OIS::KC_P}            ,
        {"[", OIS::KC_LBRACKET}     ,
        {"]", OIS::KC_RBRACKET}     ,
        {"RETURN", OIS::KC_RETURN}       ,
        {"LCONTROL", OIS::KC_LCONTROL}     ,
        {"A", OIS::KC_A}            ,
        {"S", OIS::KC_S}            ,
        {"D", OIS::KC_D}            ,
        {"F", OIS::KC_F}            ,
        {"G", OIS::KC_G}            ,
        {"H", OIS::KC_H}            ,
        {"J", OIS::KC_J}            ,
        {"K", OIS::KC_K}            ,
        {"L", OIS::KC_L}            ,
        {";", OIS::KC_SEMICOLON}    ,
        {"'", OIS::KC_APOSTROPHE}  ,
        {"`", OIS::KC_GRAVE}        ,
        {"LSHIFT", OIS::KC_LSHIFT}       ,
        {"\\", OIS::KC_BACKSLASH}    ,
        {"Z", OIS::KC_Z}            ,
        {"X", OIS::KC_X}            ,
        {"C", OIS::KC_C}            ,
        {"V", OIS::KC_V}            ,
        {"B", OIS::KC_B}            ,
        {"N", OIS::KC_N}            ,
        {"M", OIS::KC_M}            ,
        {",", OIS::KC_COMMA}        ,
        {".", OIS::KC_PERIOD}       ,
        {"/", OIS::KC_SLASH}        ,
        {"RSHIFT", OIS::KC_RSHIFT}       ,
        {"*", OIS::KC_MULTIPLY}     ,
        {"LMENU", OIS::KC_LMENU}        ,
        {"SPACE", OIS::KC_SPACE}        ,
        {"CAPITAL", OIS::KC_CAPITAL}      ,
        {"F1", OIS::KC_F1}           ,
        {"F2", OIS::KC_F2}           ,
        {"F3", OIS::KC_F3}           ,
        {"F4", OIS::KC_F4}           ,
        {"F5", OIS::KC_F5}           ,
        {"F6", OIS::KC_F6}           ,
        {"F7", OIS::KC_F7}           ,
        {"F8", OIS::KC_F8}           ,
        {"F9", OIS::KC_F9}           ,
        {"F10", OIS::KC_F10}          ,
        {"NUMLOCK", OIS::KC_NUMLOCK}      ,
        {"SCROLL", OIS::KC_SCROLL}       ,
        {"NUMPAD7", OIS::KC_NUMPAD7}      ,
        {"NUMPAD8", OIS::KC_NUMPAD8}      ,
        {"NUMPAD9", OIS::KC_NUMPAD9}      ,
        {"SUBTRACT", OIS::KC_SUBTRACT}    ,
        {"NUMPAD4", OIS::KC_NUMPAD4}      ,
        {"NUMPAD5", OIS::KC_NUMPAD5}      ,
        {"NUMPAD6", OIS::KC_NUMPAD6}      ,
        {"+", OIS::KC_ADD}          ,
        {"NUMPAD1", OIS::KC_NUMPAD1}      ,
        {"NUMPAD2", OIS::KC_NUMPAD2}      ,
        {"NUMPAD3", OIS::KC_NUMPAD3}      ,
        {"NUMPAD0", OIS::KC_NUMPAD0}      ,
        {"DECIMAL", OIS::KC_DECIMAL}      ,
        {"F11", OIS::KC_F11}          ,
        {"F12", OIS::KC_F12}          ,
        {"F13", OIS::KC_F13}          ,
        {"F14", OIS::KC_F14}          ,
        {"F15", OIS::KC_F15}          ,
        {"NUMPADEQUALS", OIS::KC_NUMPADEQUALS} ,
        {"AT", OIS::KC_AT}           ,
        {"COLON", OIS::KC_COLON}        ,
        {"UNDERLINE", OIS::KC_UNDERLINE}    ,
        {"NUMPADENTER", OIS::KC_NUMPADENTER}  ,
        {"RCONTROL", OIS::KC_RCONTROL}     ,
        {"NUMPADCOMMA", OIS::KC_NUMPADCOMMA}  ,
        {"/", OIS::KC_DIVIDE}       ,
        {"SYSRQ", OIS::KC_SYSRQ}        ,
        {"RMENU", OIS::KC_RMENU}        ,
        {"PAUSE", OIS::KC_PAUSE}        ,
        {"HOME", OIS::KC_HOME}         ,
        {"UP", OIS::KC_UP}           ,
        {"PGUP", OIS::KC_PGUP}         ,
        {"LEFT", OIS::KC_LEFT}         ,
        {"RIGHT", OIS::KC_RIGHT}        ,
        {"END", OIS::KC_END}          ,
        {"DOWN", OIS::KC_DOWN}         ,
        {"PGDOWN", OIS::KC_PGDOWN}       ,
        {"INSERT", OIS::KC_INSERT}       ,
        {"DELETE", OIS::KC_DELETE}       ,
        {"LWIN", OIS::KC_LWIN}         ,
        {"RWIN", OIS::KC_RWIN}         ,
};


